// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: greet.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServerService {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class AverageNumber
  {
    static readonly string __ServiceName = "greet.AverageNumber";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::GrpcServerService.AverageNumberRequest> __Marshaller_greet_AverageNumberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcServerService.AverageNumberRequest.Parser));
    static readonly grpc::Marshaller<global::GrpcServerService.AverageNumberResponse> __Marshaller_greet_AverageNumberResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcServerService.AverageNumberResponse.Parser));

    static readonly grpc::Method<global::GrpcServerService.AverageNumberRequest, global::GrpcServerService.AverageNumberResponse> __Method_GetAverageNumber = new grpc::Method<global::GrpcServerService.AverageNumberRequest, global::GrpcServerService.AverageNumberResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "GetAverageNumber",
        __Marshaller_greet_AverageNumberRequest,
        __Marshaller_greet_AverageNumberResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServerService.GreetReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AverageNumber</summary>
    [grpc::BindServiceMethod(typeof(AverageNumber), "BindService")]
    public abstract partial class AverageNumberBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcServerService.AverageNumberResponse> GetAverageNumber(grpc::IAsyncStreamReader<global::GrpcServerService.AverageNumberRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AverageNumber</summary>
    public partial class AverageNumberClient : grpc::ClientBase<AverageNumberClient>
    {
      /// <summary>Creates a new client for AverageNumber</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AverageNumberClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AverageNumber that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AverageNumberClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AverageNumberClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AverageNumberClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::GrpcServerService.AverageNumberRequest, global::GrpcServerService.AverageNumberResponse> GetAverageNumber(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAverageNumber(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::GrpcServerService.AverageNumberRequest, global::GrpcServerService.AverageNumberResponse> GetAverageNumber(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_GetAverageNumber, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AverageNumberClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AverageNumberClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AverageNumberBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAverageNumber, serviceImpl.GetAverageNumber).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AverageNumberBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAverageNumber, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::GrpcServerService.AverageNumberRequest, global::GrpcServerService.AverageNumberResponse>(serviceImpl.GetAverageNumber));
    }

  }
}
#endregion
